version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saksham04
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    # build: 
    # context: . 
    # dockerfile: Dockerfile
    image: saks04/fastapi-backend:latest
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=saksham04
    ports:
      - "8000:8000"
    command: ["sh", "-c", "/app/wait-for-db.sh db uvicorn main:app --host 0.0.0.0 --port 8000"]

volumes:
  pg_data:
